### PR TITLE
Closes #1

### LINKED ISSUE #1: Models and seed file
*"As a developer, I want to create models and fill my database with a seed file."*

### PR DESCRIPTION
**Pull request by whirleyt**
*Created models and seed file*

### CODE REVIEW

**Comment by whirleyt** [comment]
Hello, please review.

**Comment by whirleyt** [comment]
@ShifuYee

**Review by ahuang1822 — APPROVED** [review]
Looks great!

**Comment by ahuang1822** [comment]
Looks good!

**Pull request closed without merging**
